apiVersion: apps/v1
kind: Deployment
metadata:
  name: critter-frontend
  labels:
    app: critter-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: critter-frontend
  template:
    metadata:
      labels:
        app: critter-frontend
    spec:
      containers:
        - name: frontend
          image: bashar24k/eventportal-frontend:v1 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
          # Innovation: Liveness and Readiness Probes for Zero-Downtime
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Or NodePort depending on environment
  selector:
    app: critter-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
