apiVersion: v1
kind: Secret
metadata:
  name: critter-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<USER>:<PASS>@cluster.mongodb.net/Critter" # REPLACE BEFORE DEPLOYING
  JWT_SECRET: "your_super_secret_jwt_key_here"
  MAILTRAP_HOST: "live.smtp.mailtrap.io"
  MAILTRAP_PORT: "587"
  MAILTRAP_USER: "your_mailtrap_user"
  MAILTRAP_PASS: "your_mailtrap_pass"
  FRONTEND_URL: "http://frontend-service"
