apiVersion: v1
kind: Secret
metadata:
  name: critter-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<USER>:<PASS>@cluster.mongodb.net/Critter" # REPLACE BEFORE DEPLOYING
  JWT_SECRET: "your_super_secret_jwt_key_here"
  MAILTRAP_HOST: "sandbox.smtp.mailtrap.io"
  MAILTRAP_PORT: "2525"
  MAILTRAP_USER: "6c7944fa463243"
  MAILTRAP_PASS: "34cb0799e4fe21"
  FRONTEND_URL: "http://frontend-service"
